### PR TITLE
Update headers to 1.3.249

### PR DESCRIPTION
**Pull request by Tony-LunarG**
Also accommodate new CI system that only has python3

### CODE REVIEW

**Review by charles-lunarg — APPROVED** [review]

**Comment by dev-null-undefined** [comment]
@charles-lunarg Hey there, could you please tag the current master? Would love to apply this update to nixpkgs which are using tag for downloading the source code.

Thanks.

**Comment by dev-null-undefined** [comment]
Actually never mind it doesn't seem to build with for some reason anyhow
```
/build/source/layersvt/monitor.cpp:23:10: fatal error: containers/custom_containers.h: No such file or directory
   23 | #include "containers/custom_containers.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Building with vulkan headers  `"1.3.249"`

Steps to reproduce:
```
git clone https://github.com/NixOS/nixpkgs
cd nixpkgs
```
Edit file `pkgs/tools/graphics/vulkan-tools-lunarg/default.nix`
```patch
stdenv.mkDerivation rec {
  pname = "vulkan-tools-lunarg";
  # The version must match that in vulkan-headers
- version = "1.3.243.0";
+ version = "1.3.249";

  src = fetchFromGitHub {
   owner = "LunarG";
   repo = "VulkanTools";
-   rev = "sdk-${version}";
-   hash = "sha256-mvBP6wD1Z0VNLZ0mC4bA3i2IaBDtDr7K6XjHz4S3UA4=";
+   rev = "8f03e5af278e064b4e96309b752cf217ca9abfcf";
+   hash = "sha256-ym2r6mdI/jJe+67N66Ege79AhzJtesq0Rbc+6hdPCu4=";
   fetchSubmodules = true;
 };
```
nix build .#vulkan-tools-lunarg

**Comment by Tony-LunarG** [comment]
You need Vulkan-ValidationLayers 1.3.249.  Are you using the update_deps.py script?

**Comment by dev-null-undefined** [comment]
MB sorry I was building with wrong Vulkan-ValidationLayers sorry kind of multilayered mistake

**Pull request merged**
