### PR TITLE
vktrace: fix vkreplayer crashed on android

### PR DESCRIPTION
**Pull request by jyangsh**
Remove the dependency on libVkLayer_vktrace_layer.so.

Issue: #95

### CODE REVIEW

**Comment by cnorthrop** [comment]
I cherry-picked this change onto a working Android build (58f81124727935fa67ca41f3fe856a9148f5cdaf) and tested the build.  Getting the following errors, since pthread_cancel() is not supported by the NDK:

`
.../VulkanTools/build-android/jni/../..//vktrace/vktrace_common/vktrace_pageguard_memorycopy.cpp:200:17: error: use of undeclared identifier 'PTHREAD_CANCEL_ENABLE'
    int state = PTHREAD_CANCEL_ENABLE, oldtype;
                ^
.../VulkanTools/build-android/jni/../..//vktrace/vktrace_common/vktrace_pageguard_memorycopy.cpp:201:13: error: use of undeclared identifier 'PTHREAD_CANCEL_ASYNCHRONOUS'
    state = PTHREAD_CANCEL_ASYNCHRONOUS;
            ^
.../VulkanTools/build-android/jni/../..//vktrace/vktrace_common/vktrace_pageguard_memorycopy.cpp:219:5: error: use of undeclared identifier 'pthread_cancel'
    pthread_cancel((pthread_t)tid);
    ^
3 errors generated.
`

If I remove the change that pulls in pageguard file, I get:

`
.../VulkanTools/build-android/jni/../..//vktrace/vktrace_common/vktrace_trace_packet_utils.c:203: error: undefined reference to 'vktrace_pageguard_memcpy'
`

So this PR needs work.  I'll try to help out once we get master building generally again.

**Comment by jyangsh** [comment]
@cnorthrop , the PAGEGUARD_MEMCPY_USE_PPL_LIB define is also needed by the vkreplay module.

**Comment by cnorthrop** [comment]
LGTM - thanks!

**Comment by ardaLunarG** [comment]
merged

**Pull request closed without merging**
