### PR TITLE
vkconfig3: Layer tabs UI improvements

### PR DESCRIPTION
**Pull request by christophe-lunarg**
show_view
add_layers_path
configuration_tips

### CODE REVIEW

**Comment by ziga-lunarg** [comment]
What counts as a user-defined path? Should the SDK path not be in there?

**Comment by christophe-lunarg** [comment]
> What counts as a user-defined path? Should the SDK path not be in there?

The one added automatically thanks to $VULKAN_SDK or built-in locations.

**Comment by ziga-lunarg** [comment]
The reason I asked for this option was because if a layer in the SDK has the same version as the layer from a custom path, I don't know which one vkconfig will use.

image

**Comment by christophe-lunarg** [comment]
> The reason I asked for this option was because if a layer in the SDK has the same version as the layer from a custom path, I don't know which one vkconfig will use.
> 
> image

Ahhh, hence my comment in the Google doc.

**Pull request merged**
