### PR TITLE
Implement pageguard for Android/Linux

### PR DESCRIPTION
**Pull request by davidlunarg**

### CODE REVIEW

**Comment by davidlunarg** [comment]
@jyangsh, @mizhen  : Could you review this pull request?

This pull request is a rebase and squash of pull request #339 with a few additional small changes.

**Comment by jyangsh** [comment]
LGTM.

I think the code change is fine to be merged to the repo. After the Chinese new year, @justuswang may help verify it on arm linux platform. If any issue is found on arm linux, Justus may help handle it.

**Comment by mizhen** [comment]
Looks good to me.

**Comment by cnorthrop** [comment]
Thanks for following up on this, David!  I don't have any content readily available to verify PMB, but our smoke test using Cube is still good.

**Comment by davidlunarg** [comment]
cherry-picked to master.

**Pull request closed without merging**
