### PR TITLE
devsim: Overhaul of test script

### PR DESCRIPTION
**Pull request by mikew-lunarg**
Overhaul of tests/devsim_layer_test.sh:
- use new "vulkaninfo -j" functionality.
- use jq to extract and sort elements of output file.
- use jq to compare output file against gold.
- better error reporting.
- fix a couple bugs.

Update new devsim_test1_in*.json input file fragments.

Update CMakeLists for new files.

Regenerate goldfile for new output and formatting.

Change-Id: I6406199f8cbe75eed6a7ffd3a5848d7ee89fee22

### CODE REVIEW

**Comment by mikew-lunarg** [comment]
Reviewers, sorry for the churn.  This script worked on internal CI but is failing on TravisCI.  (vulkaninfo is returning status 255)  I'm diagnosing and will mention when Travis is happy.

**Comment by mikew-lunarg** [comment]
Update: This PR depends upon a newly added feature of vulkaninfo, and needs a couple refinements for our usecase.

Feel free to review the first commit of this PR, as it will not substantially change.
But it will need the vulkaninfo changes before CI will succeed.

**Comment by mikew-lunarg** [comment]
OK, we're good now, please review.

Refinements have been made, the LVL submodule is updated to get a new vulkaninfo, and it is passing

**Comment by shannon-lunarg** [comment]
Looks good to me but I have a question:
When I run the devsim layer test I get the following output.
```
[ RUN      ] ./devsim_layer_test.sh
true
[  PASSED  ] ./devsim_layer_test.sh
```
If a "true" value is expected should something be added to inform the user what exactly is true without having to look at the script?

**Comment by mikew-lunarg** [comment]
Ah, fair point.  That's actually the output from jq doing the compare of
the JSON files.
I will redirect that to keep the output clean.
Thanks

**Comment by karl-lunarg** [comment]
Looks OK to me with the fix to squelch the jq output.

Do you think it would be a good idea to clean up the temp files at the end?

Since this script is typically run from the build directory, it doesn't seem that important to me, but you can decide.

**Comment by mikew-lunarg** [comment]
submitted change to send jq output to /dev/null

**Comment by mikew-lunarg** [comment]
@karl-lunarg I purposely left the temp files to aid diagnosis if there's a failure.    As you say, they're in the build dir, so dont linger after cleaning up.

**Comment by karl-lunarg** [comment]
yep, that's fine.

**Comment by cnorthrop** [comment]
vulkaninfo isn't supported on Android, so we need to get that sorted out.  Will work with @mikew-lunarg offline.

**Comment by mark-lunarg** [comment]
Are you thinking you'll ditch this and replace it with a python script, or are you planning to add a powershell version to get Windows coverage?

**Comment by mikew-lunarg** [comment]
This script has only ever been for Linux, due to dependencies on Linux text
processing tools.

To gain multi-platform coverage, in the future I intend to port this to
Python.

**Comment by mikew-lunarg** [comment]
@cnorthrop Can this PR be pushed to master in its current form while awaiting resolution to the "vulkaninfo on Android" issue?  If not, can this PR be adjusted to make it more acceptable?  There are upcoming PRs that depend on this one.

**Comment by mikew-lunarg** [comment]
Rebasing this PR to _not_ depend upon #411

**Comment by mikew-lunarg** [comment]
Postponing the push of this PR to a time when vulkaninfo is enhanced to work on Android.

**Comment by cnorthrop** [comment]
I added bare bones support for compiling vulkaninfo for Android on this [branch](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/tree/vulkaninfo_android).  It only prints out a few lines before segfaulting, but it has a pulse. If someone has time to take a look at it before I do, go for it. Should be pretty obvious what's wrong with a debugger connected.

**Comment by mikew-lunarg** [comment]
Adjusted jq stdout/stderr redirection to keep test output clean.

**Comment by mikew-lunarg** [comment]
Due to Android not yet supporting vulkaninfo, I'm abandoning this PR and will replace with a PR that leaves vkjson_info testcase in place, and adds the vulkaninfo testcase.

See branch [mikew_devsim_test2](https://github.com/LunarG/VulkanTools/tree/mikew_devsim_test2)

**Comment by mikew-lunarg** [comment]
Replaced by PR #427

**Pull request closed without merging**
