### PR TITLE
devsim: Reactivate ArrayOfExtensionProperties

### PR DESCRIPTION
**Pull request by jeremyk-lunarg**
Added back in code to override the list of device extensions.

Addresses issue #985

### CODE REVIEW

**Review by dustin-lunarg — APPROVED** [review]

**Review by christophe-lunarg — APPROVED** [review]
Approved but I can't tell I have enough knowledge to give relevant feedback.

**Comment by mark-lunarg** [comment]
What other changes were made after the PR as approved -- do we need to redo the code review @jeremyk?

**Comment by jeremyk-lunarg** [comment]
@mark-lunarg since this feature has been off for so long, I thought I would add a setting to specifically turn it on, so that I don't accidentally break applications downstream that use config files including an extension list.

**Review by lunarpapillo — APPROVED** [review]
I reviewed reasonably thoroughly and found no issues.

**Pull request merged**
