### PR TITLE
vkreplay: fix pNext exceptions during playback

### PR DESCRIPTION
**Pull request by xooiamd**
Game title under test throws exception in processing
the pNext struct in both vkGetImageMemoryRequirements2 and
vkGetBufferMemoryRequirements2 calls during playback.
Split the calls with their KHR extension calls and remove
process pNext struct for these calls as there is no valid
pointers to be processed for these calls. This fix the
game playback exception issue.

VKTRACE-120

Change-Id: I5590abc4f019621ff79c41cee34e04ff1c972330

### CODE REVIEW

**Comment by davidlunarg** [comment]
I don't understand why the pNext structures should not be processed. Is it because the pNext pointers or the structures they point to are invalid? If so, it seems that should be fixed rather than not processing them. In the future, an extension may be added that uses the pNext structures, and it would be good if the code to process them was already in place.

**Comment by xooiamd** [comment]
hi @davidlunarg , from the doc, 
https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/vkGetBufferMemoryRequirements2.html
https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkMemoryRequirements2.html
https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkMemoryDedicatedRequirements.html

for vkGetBufferMemoryRequirements2 or vkGetImageMemoryRequirements2 , the pNext chain of the VkMemoryRequirements2 structure which is in the parameter of  pMemoryRequirements may have a  VkMemoryDedicatedRequirements structure but this structure contain no pointers to be interpreted/ processed during the playback.

**Comment by davidlunarg** [comment]
I have looked at this some more, and still believe the calls to process the pNext structures are needed. Even though the pNext structures passed in by current apps do not have pointers that need to be interpreted, future apps may have them. The vkMemoryDedicatedRequirements structure may not have pointers to be interpreted, but other pNext structures in the future might.

**Comment by xooiamd** [comment]
hi @davidlunarg , sorry I remembered why i removed these pnext, because they are already beiing handled by the interpret_body_as_ function in the vktrace_vk_vk_packets.h function due to recent fix to the generation script

**Pull request merged**
