### PR TITLE
vktrace: macOS targeting Android

### PR DESCRIPTION
**Pull request by cnorthrop**
This series gets all three host platforms (Linux, Windows, macOS) working with vktrace on Android.

### CODE REVIEW

**Comment by davidlunarg** [comment]
In file /vktrace/src/vktrace_common/CMakeLists.txt:
@@ -34,7 +34,7 @@ set_source_files_properties( ${CXX_SRC_LIST} PROPERTIES LANGUAGE CXX)
 file( GLOB_RECURSE HDRS *.[h|inl] )
 
 if (NOT MSVC)
-    add_compiler_flag("-fPIC -std=c++11")
+    add_cpp_compiler_flag("-fPIC -std=c++11")
 endif()

Will this change affect built on Linux? Is it OK to call add_cpp_compiler_flag vs add_compiler_flag?

**Comment by davidlunarg** [comment]
I am in the process of making changes to Linux to detect changes to Persistently Mapped Buffers and  to add the buffers to the trace file when the PMB changes. Changes to a PMB will be detected as described in https://www.kernel.org/doc/Documentation/vm/soft-dirty.txt. Does OSX have support for /proc/<pid>/pagemap and /proc/<pid>/clear_refs?

**Comment by cnorthrop** [comment]
It will affect Linux.  Clang got upset when -std=c++11 was set for CMAKE_C_FLAGS as add_compiler_flag() does.

Looking closer, PIC can be set for C and C++, so I'll re-enable it like so:

    add_c_compiler_flag("-fPIC")
    add_cpp_compiler_flag("-fPIC -std=c++11")

**Comment by ardaLunarG** [comment]
Getting this error while compiling on Linux:

[ 66%] Linking C shared library ../../libVkLayer_vktrace_layer.so
/usr/bin/ld: ../vktrace_common/libvktrace_common.a(vktrace_filelike.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
../vktrace_common/libvktrace_common.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
vktrace/src/vktrace_layer/CMakeFiles/VkLayer_vktrace_layer.dir/build.make:308: recipe for target 'vktrace/libVkLayer_vktrace_layer.so' failed
make[2]: *** [vktrace/libVkLayer_vktrace_layer.so] Error 1
CMakeFiles/Makefile2:3057: recipe for target 'vktrace/src/vktrace_layer/CMakeFiles/VkLayer_vktrace_layer.dir/all' failed
make[1]: *** [vktrace/src/vktrace_layer/CMakeFiles/VkLayer_vktrace_layer.dir/all] Error 2
Makefile:127: recipe for target 'all' failed

**Comment by cnorthrop** [comment]
Android supports /proc//pagemap and /proc//clear_refs so I'm looking forward to porting it.  :)  I'm not running any Vulkan code on OSX, just listening for Vulkan calls over sockets with vktrace, so hopefully that won't matter.

**Comment by cnorthrop** [comment]
Arda, adding -fPIC back should help.  I'm doing that now.

**Comment by cnorthrop** [comment]
Branch updated, let me know if it helps.

FWIW, I'm roughly 50% done getting continuous integration going for this repo on our side.

**Comment by ardaLunarG** [comment]
merged

**Pull request closed without merging**
