### PR TITLE
Add VK_LAYER_KHRONOS_json_gen layer for Vulkan SC development

### PR DESCRIPTION
**Pull request by dgkoch**
- Use generated code to create layer.
  - This reuses the layer generator from api_dump.
- Intercepts the necessary APIs, dumps json data.
- Generates VkDeviceObjectReservationCreateInfo dump
- Use VK_EXT_private_data extension for tracking objects.
  - VK_EXT_private_data is part of core Vulkan 1.3. Prior to that,
  - it was an extension. So, check the Vulkan version before using
  - the core/EXT version of this feature.
- Implement VK_EXT_pipeline_properties in JSON generation layer
  - to use: - enable VK_EXT_pipeline_properties extension - call vkGetPipelinePropertiesEXT after vkCreateComputePipelines or vkCreateGraphicsPipelines (you'll need to use vkGetProcAddress to retrieve the vkGetPipelinePropertiesEXT entry-point)
  - Use OpenSSL MD5 hashing algorithm. std::hash does not guarantee same output hash generation with the same input always (standard does not guarantee this on multiple executions).
  - This change also adds OpenSSL dependency in cmake.
- Add Json Generation Layer Tests
  - This contains a script (jsonGenLayerTests.py) which runs a small layer enabled vulkan app and then compares the generated json files with the golden set of files.
  - The app also verifies the functionality of VK_EXT_pipeline_properties by comparing the UUID generated from vkGetPipelinePropertiesEXT and the golden UUID.

To build:

- mkdir build
- ./update_external_sources.sh
- cd build
- ../scripts/update_deps.py cmake -C helper.cmake .. 
- cmake --build . --parallel

### CODE REVIEW

**Comment by dgkoch** [comment]
How do we access the CI logs?  I'd seen some previously from the first CI run, but I can't find any now..

**Comment by lunarpapillo** [comment]
> How do we access the CI logs? I'd seen some previously from the first CI run, but I can't find any now..

In theory, the curator should be able to send them to you, if the curator knows your e-mail address.  I think I can find them and send them if you can get me your e-mail address...

**Comment by dgkoch** [comment]
> > How do we access the CI logs? I'd seen some previously from the first CI run, but I can't find any now..
> 
> In theory, the curator should be able to send them to you, if the curator knows your e-mail address. I think I can find them and send them if you can get me your e-mail address...

@lunarpapillo "firstinitiallastname@myemployer.com"

**Comment by lunarpapillo** [comment]
E-mail sent, thanks.  There should be six separate attached logs, one for each CI configuration.  Please let me know if any don't get through (you should have my return e-mail after the forwarded e-mail arrives).

**Comment by charles-lunarg** [comment]
Can you add a description of this layer and how developers will use it?
Just reading the PR doesn't give me a good picture on what the purpose of the VK_LAYER_KHRONOS_json_gen layer is. Is there documentation elsewhere that describes the purpose of the layer?

**Comment by KarenGhavam-lunarG** [comment]
From other conversations I have learned that this is a Vulkan layer which is intended to be used with a Vulkan application in order to help transition it to Vulkan safety critical and it will be used for Vulkan safety critical development.

Although this is a Vulkan layer, it's intent is to be used by those developing a Vulkan safety critical application. This repository is focused on tools for Vulkan application developers and I don't believe is the best home for this layer. I suspect there will be other tools needed for folks developing safety critical applications (such as a safety critical version of vulkaninfo that is homed in Vulkan-Tools) and it is probably better to create a safety critical focused repository with such tools. This will aid in discovery and ease of use by folks developing safety critical applications.

**Comment by KarenGhavam-lunarG** [comment]
Since this repository is tools for Vulkan application developers, and not tools for Vulkan Safety Critical developers, closing this PR.

**Pull request closed without merging**
