### PR TITLE
layers: screenshot: Update doc and rename env var

### PR DESCRIPTION
**Pull request by joey-lunarg**
Renamed _VK_SCREENSHOT to VK_SCREENSHOT_LAYERS. Old name will still work. Some
additional refactoring. Updated README.md

Change-Id: I20ef445b8936a294dc2e12fab5e4b966977a072b

### CODE REVIEW

**Comment by cnorthrop** [comment]
Looking at the diff, you've renamed it to VK_SCREENSHOT_FRAMES, which makes sense.  VK_SCREENSHOT_LAYERS does not, so you'll need to update the commit message.

I'll test this on Android and let you know how it goes.

**Comment by cnorthrop** [comment]
Broken on Android.  env_var_old is only defined with Windows and Linux, but is used unconditionally in QueuePresentKHR.  You can either make the use also conditional, or add an env_var_old to Android section and use the same string.  The latter is cleaner, if redundant.

**Comment by joey-lunarg** [comment]
Thanks for the feedback Cody-
Fixed the message and added the dummy variable for android. Lemme know if this fixes it.

**Comment by cnorthrop** [comment]
Thanks, Joey, this works now.  Although I would prefer the Android env_var_old to be "debug.vulkan.screenshot", just like env_var, since we never supported the desktop var.
How about we just use:

    -const char *env_var_old = "_VK_SCREENSHOT";
     const char* env_var = "debug.vulkan.screenshot";
    +const char *env_var_old = env_var;

**Comment by joey-lunarg** [comment]
Ok makes sense, updated

**Comment by ardaLunarG** [comment]
Hey Cody,
Once you are OK please +1 and I will merge the pull req.

**Comment by ardaLunarG** [comment]
merged

**Pull request closed without merging**
