### PR TITLE
vktrace: modify help text, fix frame range parsing error

### PR DESCRIPTION
**Pull request by mizhen**
modify help text, fix frame range parsing error

modify help text of screenshot command for vktrace/vkreplay, fix frame range parsing error make it output error message for extra input.

Change-Id: I20fe77eae7c33a26f5354079d03ad0f9971d5ff9

### CODE REVIEW

**Comment by davidlunarg** [comment]
The method checkScreenShotFrameRangeString returns true if the string passed in is "2--2". It should return false.

When the range specified with -s for vktrace/replay has a bad format, the error message should include the help text. Also, the error message describing the error in the range doesn't need to be so verbose. Attached is a patch file with my proposed changes. If my changes are used, the method initScreenShotFrameRange could be simplified to return true or false, rather than a specific error number.

[p.patch.zip](https://github.com/LunarG/VulkanTools/files/736392/p.patch.zip)

**Comment by mizhen** [comment]
The function is used to check the following: rangeString is valid, every char is '0'-'9' or '-', char '-' count <= 2. It should return true. initScreenShotFrameRange function can handle errors like frameCount < 0. 

The patch file looks good. Thanks, David.

**Comment by davidlunarg** [comment]
Could you resubmit with my patch? I think we would then be good to go.

**Comment by ardaLunarG** [comment]
As Ming approved David's changes I push both of them to master.

**Pull request closed without merging**
