### PR TITLE
Add mutex lock for all manual and autogenerated hooked API when trim capture is enabled.

### PR DESCRIPTION
**Pull request by mizhen**
Add mutex lock for all manual and autogenerated hooked API when trim capture is enabled.
declare extern mutex variable in vktrace_lib_trim header file.

### CODE REVIEW

**Comment by mizhen** [comment]
The pull request is second part of replacement of pull request #645, the first part of the replacement is https://github.com/LunarG/VulkanTools/pull/669

**Comment by justuswang** [comment]
@mizhen, is it possible to always have the mutex lock no matter trim capture is enabled or not?
Otherwise issue #473 "multi-thread API calls are re-ordered in trace file" will happen again.

**Comment by mizhen** [comment]
Yes. If considering enable the lock when capturing without trim, an environment variable might be needed as a switch.

**Comment by davidlunarg** [comment]
It seems it would be better not to use an environment variable to address a problem such as reordering of api calls.

**Comment by xooiamd** [comment]
Hi, there is some performance drop if always have mutex lock, which is why we enable it only during trim capture. But we could add an option in vktrace to turn it  on/off. Any comments/advice? Thanks

**Comment by davidlunarg** [comment]
It looks like the current set of commits enable the use of a mutex for all api calls. Is this correct?

To enable the use of a mutex,  an option can be added to vktrace.

**Comment by xooiamd** [comment]
hi, the current commit is using a customized mutex lock guard class (named TrimLockGuard) which is declared in vktrace_lib_trim.h file. This class will only lock/unlock mutex when g_trimEnabled is set to true. Although all api calls has TrimLockGuard, but the use of mutex is only enabled by g_trimEnabled. 
Yes, we can add an option to enable the use of mutex.

**Comment by mizhen** [comment]
The pull request is replaced by https://github.com/LunarG/VulkanTools/pull/718

**Pull request closed without merging**
