### PR TITLE
VulkanTools: screenshot commandline options

### PR DESCRIPTION
**Pull request by ardaLunarG**
Command line option:

The user could specify the frames with a range.

--ScreenShot <start_frame> - -
--ScreenShot <start_frame> -
--ScreenShot all
or
-s <start_frame> - -
-s <start_frame> -
-s all

Change-Id: I9285c0aff17317f962d010cee96dbbe445866352

### CODE REVIEW

**Comment by ardaLunarG** [comment]
Capitalized Screenshot in the commit. Thanks Mark

**Comment by ardaLunarG** [comment]
Capturing David's comment on previous PR.

-s 1-2-x does not generate an error but -s 1-x-2 does.
-s 1-2-3-4 does not generate an error

The help text should be modified as in my feedback in pull request 141.

**Comment by cnorthrop** [comment]
I'll get it compiling for Android.

Any tests to go along with this new functionality?

**Comment by ardaLunarG** [comment]
Thanks Cody, no tests yet.

**Comment by cnorthrop** [comment]
If you cherry-pick the following commit, this should build on Android:  f056484e2c95d062c4d67cf4f24273d996d9df5e

**Comment by ardaLunarG** [comment]
Thanks Ming and Cody! Pushed these patches to master.

**Pull request closed without merging**
