### PR TITLE
vktrace: Fixes for Android

### PR DESCRIPTION
**Pull request by cnorthrop**
Turned off some code that doesn't work on Android yet.
Also removed an unused variable.

Verified with:

    ./build_vktracereplay.sh
    ./vktracereplay.sh --serial <...> --abi armeabi-v7a --apk ../demos/android/cube-with-layers/bin/NativeActivity-debug.apk --package com.example.CubeWithLayers --activity android.app.NativeActivity --frame 100

### CODE REVIEW

**Comment by cnorthrop** [comment]
It exists, but cannot be opened yet.  It may be a limitation on the APK or vktrace_layer itself.  We're still trying to determine how to use this on Android.  We don't want to feature enable yet, actually.  I thought I'd disabled it in the earlier series, but the new code appears to be called unconditionally.

**Comment by davidlunarg** [comment]
+1

**Comment by mark-lunarg** [comment]
Hey @cnorthrop, I'm trying to get some stuff through our build farm and so tried this PR -- it fixes the android failures but croaks in Windows like so:

33>C:\dev\xgl\VulkanTools\vktrace\src\vktrace_layer\vktrace_lib_pageguardcapture.cpp(381): error C2039: 'pageRefsDirtyClear': is not a member of 'PageGuardCapture'

**Comment by mark-lunarg** [comment]
Looks like the ifdef below might need to go around the entire function including the declaration?

`#if defined(PLATFORM_LINUX) && !defined(ANDROID)`

Also, the ifdef in the header file might also need the && !defined(ANDROID) ?

**Comment by cnorthrop** [comment]
Thanks, Mark, I'll revisit this branch.

**Comment by MarkY-LunarG** [comment]
Is this going to be fixed soon?  I'm holding changes until this is resolved.

Thanks,
markY

**Comment by cnorthrop** [comment]
Working on it now.  Didn't think Android breakage would actually hold anything up.

**Comment by cnorthrop** [comment]
Btw, master is only broken functionally for Android.  I believe the build is fine if you want to commit something.

**Comment by cnorthrop** [comment]
I'm confusing branches - I've got Windows booted up and will get it tested this time.  It is a slow box, but definitely before end of day.

**Comment by cnorthrop** [comment]
Okay, I think this is ready now.  Cube passes on Android and Windows.  I can't get the smoke portion of _vktracereplay.ps1 to work on Windows, I think that support is in flight.

**Comment by jyangsh** [comment]
/build-android/jni/../..//vktrace/src/vktrace_common/vktrace_trace_packet_utils.c:203: error: undefined reference to 'vktrace_pageguard_memcpy'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [obj/local/armeabi-v7a/libvkreplay.so] Error 1

It seems need add the "vktrace_pageguard_memorycopy.cpp" to the vkreplay build for android.

And so the pageguard feature still does not work for the android build, right?

**Comment by cnorthrop** [comment]
@jyangsh I'm not seeing that error on my end.  Are you on the most recent version of the branch?  I've done a couple forced updates.  Do you build with either of the build_vktracereplay scripts?

Right, we don't expect pageguard to work yet.  We're exploring ways to get it working soon.

**Comment by ardaLunarG** [comment]
merged

**Comment by jyangsh** [comment]
@cnorthrop, thanks, I retried the latest master branch code, the build is good.

Hope the pageguard is ready for android soon, some UE4 demos tracing depends on it. :)

**Pull request closed without merging**
