### PR TITLE
cube: Add direct to display support

### PR DESCRIPTION
**Pull request by damienleone**
Although this extension is platform agnostic, this commit only enables
it on Linux because this is the only platform I am able to test.

Direct to display is enabled by passing '-DDEMOS_WSI_SELECTION=DISPLAY'
to cmake.

### CODE REVIEW

**Comment by damienleone** [comment]
I'm not sure if that pull request is properly formed as there has been a conflict that I manually resolved from the github interface.  Please let me know.

**Comment by ardaLunarG** [comment]
Hey Damien,

Thanks for the PR. 
Patch looks OK only the wrong repo.

We will review it more, if functionality is OK I will merge it to the right repo for you.

**Comment by ardaLunarG** [comment]
Hey Damien,

Rebased and pushed the right repo.

cube: Add direct to display support [1430](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/1430)

Please review as I rebased and when you confirm I will push.
And soon after it will come back to this repo.

**Comment by ardaLunarG** [comment]
Merged to LVL and VT

**Pull request closed without merging**
